### ISSUE TITLE
Found another OSF

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-procedures#14]
There is additional content here: https://osf.io/h9vqt/wiki/home/

Some of it might be good to "rescue" and merge into this book.  Haven't looked through it yet, but we can use this issue to discuss.

**Comment by KristinaRiemer** [comment]
Proposal to add a "Tracking Impact" page to maybe the "Group Procedures" section? This could include an expanded version of the "Metrics of success" list, along with links/instructions for the effort spreadsheet, networking spreadsheet, maybe some other things...

**Comment by KristinaRiemer** [comment]
Then a secondary idea is to move the "Other / Complementary Resources for Computing / Data Science on campus" content to an internal doc on the CCT DS Google Drive. DS activities, groups, and people are UA are constantly changing, so while it would be useful for us to have a list of these things (and maybe compare/contrast what they're doing to what we're doing), I don't think we want to be responsible for curating a public list?

**Comment by KristinaRiemer** [comment]
Moved the last section to a [new doc](https://docs.google.com/document/d/1fJko5KrYnHTAIKePUH5vyXrrdeq-9rR5RilLMRRaVxA/edit).

**Comment by KristinaRiemer** [comment]
All OSF links have been taken care of!
