### ISSUE TITLE
Minor link updates to HackMD on Incubator page

### ISSUE THREAD

**Issue by Chris-Schnaufer** [cct-datascience/group-procedures#19]
On [line 42](https://github.com/cct-datascience/group-procedures/blob/fb091d91b530dd03ae6a808bb744cfaa5921a867/incubator.qmd#L42) of incubator.qmd

1. change the "here" text to "on HackMD" (keeping the link)
2. have the link open in a new tab (add `{:target="_blank"}` to after closing link right-parend? - not tested)
3. keep old link as "old notes" (or similar text) - see comment below for new link 

**Notes:**
use \&\#x2197\; (&#x2197;) on links to indicate a new tab opens

**Comment by Aariq** [comment]
Turns out there is a setting in _quarto.yml to turn this on for all external links: https://quarto.org/docs/output-formats/html-basics.html#external-links
