### ISSUE TITLE
Add pipelines newsletter

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/group-procedures#24]
## Suggest an Edit

What it says now:
There's a list of places to advertise on the [OSF communications page](https://osf.io/tzmhp/wiki/Public%20Communications/) (which hasn't been moved over yet?). 
What it should say:
Should add the libraries pipelines newsletter (maybe send directly to Jeff Oliver?)

**Comment by Aariq** [comment]
There's a PR to move it over here: https://github.com/cct-datascience/group-procedures/pull/23

**Comment by Aariq** [comment]
maybe just add this in a PR review?

**Comment by Aariq** [comment]
I'll add it to the [spreadsheet](https://docs.google.com/spreadsheets/d/155tcna1dMWwsZymdKFZPCrnZf3xocw4hPv1JKwOu9MQ/edit?gid=0#gid=0), although it's not clear how to contribute to it.
