### ISSUE TITLE
Update zoom instructions

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-procedures#26]
## Suggest an Edit

What it says now:
https://cct-datascience.github.io/group-procedures/workshops.html#creating-a-template-for-workshop-zoom-meetings

What it should say:
I think zoom has changed the way you add a registration survey.  There's a new "survey" tab—maybe that's how you do it?

**Comment by KristinaRiemer** [comment]
@diazrenata did this yesterday, and it was a struggle!

**Comment by Aariq** [comment]
Ok, it has not actually changed, but if I had trouble following my own instructions, they could probably be improved.  Will leave this open as a reminder to add additional screenshots. 

We should also explore the survey tab—I think it is maybe new and looks like a way to do post-workshop surveys.
