### ISSUE TITLE
Check GP book covers lab notebook topics

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/group-procedures#30]
Using [this article](https://elifesciences.org/articles/88853) on lab notebooks to promote positive and transparent group culture.

**Comment by Aariq** [comment]
Pretty sure we hit all the main points in this article with our book:

- "Lab members will have a pathway for accountability" see our [code of conduct](https://cct-datascience.github.io/group-procedures/code-of-conduct.html) and [group expectations](https://cct-datascience.github.io/group-procedures/group-expectations.html)
- "Lab members will feel empowered" everyone is encouraged to edit this book and we even have dedicated time for discussion group processes/policies/procedures
- "Lab members will understand how the lab functions." I think this is well covered, but always evolving
