### ISSUE TITLE
Add instructions for how to use group's listserv

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/group-procedures#34]
## Suggest an Edit

What it says now:
Only reference to CCT DS listserv management software Emma is on the workshops page

What it should say:
Instructions for how to get added to our Emma account and how to send out a campaign. I'm not sure where this should go, maybe on the group communications or outreach or something?

**Comment by Aariq** [comment]
Could be in outreach but should be cross-referenced in onboarding also probably.

**Comment by Aariq** [comment]
I'm assigning @diazrenata only because she got access most recently of all of us

**Comment by Aariq** [comment]
We're going to switch from Emma to something else, so wait to update this until the switch.
