### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-procedures#49]
I suspect maybe CC BY-NC-SA 4.0 is appropriate, but we should go through the CC licence wizard thing as a group perhaps.

https://creativecommons.org/licenses/by-nc-sa/4.0/

https://chooser-beta.creativecommons.org/

After a licence is chosen add to CITATION.cff 
```
license: CC-BY-NC-SA-4.0
```

**Comment by KristinaRiemer** [comment]
I didn't know they had a tool for choosing licenses! 

Is there a reason to not use the most permissive one, CC BY?

**Comment by Aariq** [comment]
I would be fine with CC BY

**Comment by Aariq** [comment]
Sounds good. I'll add the CC BY license to #50
