### ISSUE TITLE
Fix up spreadsheets for workshop registrant info

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/group-procedures#86]
Currently there are two separate google sheets documents corresponding to two different zoom reports:

- https://docs.google.com/spreadsheets/d/15E5JDNiVr9aCWYE4iFSirvwzdllLtWEEZAwYi3_TScE/
- https://docs.google.com/spreadsheets/d/1SU8Wtx7Ku1IMv8DOAU-37E12-AZP0CjnRy1vPSkmNGQ/

For one of them, the column headers don't match the CSV exported from Zoom, which sucks for copy paste.  Do we need both?  Should they be two tabs in the same sheet?  What will we do with this info?

**Comment by Aariq** [comment]
My thoughts are that if/when we do anything with this info, we can do it programmatically (i.e. with spreadsheet formulae on a separate tab or with R), so let's make this step as *simple* as possible.  E.g. drop each .csv in a Google Drive folder or copy and paste verbatim (all columns) into two different tabs of a Google Sheets doc.

**Comment by KristinaRiemer** [comment]
Lead the two spreadsheets as they are. Created two new folders in GDrive to put the raw, downloaded reports from Zoom. We'll want to create a script to summarize that data, put in GH repo.
